
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with your desired Node.js version
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: nodejs-artifacts
          path: ./dist  # Adjust to your build output path
          if-no-files-found: error
